### ISSUE TITLE
why there is no 0.5* in the equation of the derivative of sate(t)

### ISSUE THREAD

**Issue by tinymindxx** [hyperdo/julia-lstm#1]
in nicodjimenez's blog,  derivative of s(t) is get by this equation,
![image](https://user-images.githubusercontent.com/5286725/36954928-1eb2c4b4-2060-11e8-85ac-5aa3079e977d.png)
i wonder why the left of this equation is equal to the right. 
in my opinion, left = 0.5*right.
I am new to nn and lstm,  and i will appreciate if you could give some tips on this question, thanks!

**Comment by ehknight** [comment]
@frozenxia, will try to help, but it's when a while since I last looked at this implementation/blog post. That above derivation doesn't look right — maybe the author meant that `dL(t)/ds(t) = ∂L(t)/∂hi(t) • dhi(t)/dsi(t) + ∂L(t)/∂hi(t+1) • dhi(t+1)/dsi(t)` (honestly not sure about this either; notation is a bit confusing). If this is the case, you'll need to unroll the sum further, e.g. `dL(t)/ds(t) = Σ_i (∂L(t)/∂hi(t+i) • ∂hi(t+i)/∂si(t))`. While I guess you're somewhat correct in trying to multiply it by `1/2`, I don't think that was the intention.

**Comment by tinymindxx** [comment]
@hyperdo  thanks for your reply!

it's not my intention to multiply 0.5 to the right. In my opinion, we don't need  **top_diff_s** at all, and in the test code, if we remove  **top_diff_s**,  it's more likely to get a lower loss.

below is the detail:
https://github.com/nicodjimenez/lstm/issues/33

thanks  for your reply again!

**Comment by ehknight** [comment]
Interesting! Have you tried it on different datasets, and do you think the math works out? For now, will close this issue as discussion seems to have converged to nicodjimenez/lstm#33, but feel free to re-open if needed.
